"""add comments table

Revision ID: 51adc2175062
Revises: c9142fe9cb10
Create Date: 2026-05-15 22:18:16.450823

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '51adc2175062'
down_revision: Union[str, Sequence[str], None] = 'c9142fe9cb10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
