"""add description to tickets

Revision ID: c9142fe9cb10
Revises: 0de2fd07dea8
Create Date: 2026-05-15 22:18:00.701891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9142fe9cb10'
down_revision: Union[str, Sequence[str], None] = '0de2fd07dea8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'description')
    # ### end Alembic commands ###
